version: '3'
services:

  kimai:
    image: kimai/kimai2:prod
    environment:
        - APP_ENV=prod
        - DATABASE_URL=mysql://petrus@db/kimai
        - MYSQL_DATABASE=kimai
        - MYSQL_USER=kimai
        - MYSQL_PASSWORD=kimai
        - MYSQL_ROOT_PASSWORD=nx9010

    ports:
        - 8080:8080
    restart: always
